// Prix de livraison par ville (source : Excel fourni par le client)
// Livraison gratuite à partir de 499 DH

export interface City {
  name: string
  price: number
}

export const FREE_DELIVERY_THRESHOLD = 499

export const CITIES: City[] = [
  { name: "CASA", price: 19 },
  { name: "BOUSKOURA", price: 29 },
  { name: "BENI MELLAL", price: 35 },
  { name: "BEJAAD", price: 39 },
  { name: "AZILAL", price: 45 },
  { name: "ERRAHMA", price: 29 },
  { name: "KHORIBGA", price: 35 },
  { name: "BOUJNIBA", price: 39 },
  { name: "FQUIH BEN SALAH", price: 45 },
  { name: "DAR BOUAZZA", price: 29 },
  { name: "BERRECHID", price: 35 },
  { name: "KASBA TADLA", price: 39 },
  { name: "SEBT OULAD NEMMA", price: 45 },
  { name: "MOHAMMEDIA", price: 29 },
  { name: "SETTAT", price: 35 },
  { name: "KHNIFERA", price: 39 },
  { name: "EL KSIBA", price: 45 },
  { name: "MEDIOUNA", price: 29 },
  { name: "HAD SOUALEM", price: 35 },
  { name: "MRIRT", price: 39 },
  { name: "LOULAD", price: 45 },
  { name: "NOUACER", price: 29 },
  { name: "BOUZNIKA", price: 35 },
  { name: "OUED ZEM", price: 39 },
  { name: "AL KEBAB", price: 45 },
  { name: "AIN HARROUDA", price: 29 },
  { name: "SIDI REHAL", price: 35 },
  { name: "ZAOUIAT CHEIKH", price: 39 },
  { name: "RAS EL AIN", price: 45 },
  { name: "TIT MELIL", price: 29 },
  { name: "EL JADIDA", price: 35 },
  { name: "BOUNOIR", price: 39 },
  { name: "SIDI EL AYEDI", price: 45 },
  { name: "DEROUA", price: 29 },
  { name: "BENSLIMANE", price: 35 },
  { name: "HETTAN", price: 39 },
  { name: "OULAD SAID", price: 45 },
  { name: "TAMARIS", price: 29 },
  { name: "CHALLALAT MOHAMMEDIA", price: 35 },
  { name: "OULAD YAICH", price: 39 },
  { name: "OULAD ABBOU", price: 45 },
  { name: "BNI YAKHLEF", price: 35 },
  { name: "IGHREM LAALAM", price: 39 },
  { name: "EL BOROUJ", price: 45 },
  { name: "EL MANSOURIA", price: 35 },
  { name: "TAGZIRT", price: 39 },
  { name: "GUISSER", price: 45 },
  { name: "OULAD AZZOUZ", price: 35 },
  { name: "OULAD YOUSSEF", price: 39 },
  { name: "BIR JDID", price: 45 },
  { name: "FES", price: 35 },
  { name: "OULAD ALI", price: 39 },
  { name: "OULAD FREJ", price: 45 },
  { name: "MEKNES", price: 35 },
  { name: "OULAD ZMAM", price: 39 },
  { name: "SIDI SMAIL", price: 45 },
  { name: "NADOR", price: 35 },
  { name: "SIDI JABER", price: 39 },
  { name: "MESSAWERR RASSO", price: 45 },
  { name: "OUJDA", price: 35 },
  { name: "SOUK SEBT", price: 39 },
  { name: "EL HAOUZIA", price: 45 },
  { name: "MARRAKECH", price: 35 },
  { name: "DAR OULD ZIDOUH", price: 39 },
  { name: "OULAD AMRANE", price: 45 },
  { name: "ESSAOUIRA", price: 35 },
  { name: "OULAD AYAD", price: 39 },
  { name: "SIDI HAJJAJ", price: 45 },
  { name: "SAFI", price: 35 },
  { name: "SIDI AISSA", price: 39 },
  { name: "ARFOUD", price: 45 },
  { name: "SIDI BOUZID-SAFI", price: 35 },
  { name: "OULAD M'BARK", price: 39 },
  { name: "ER-RICH", price: 45 },
  { name: "RABAT", price: 35 },
  { name: "AFOURAR", price: 39 },
  { name: "ERRACHIDIA", price: 45 },
  { name: "KENITRA", price: 35 },
  { name: "TIMOULILT", price: 39 },
  { name: "KELAAT M'GOUNA", price: 45 },
  { name: "SALE", price: 35 },
  { name: "BENI AYAT", price: 39 },
  { name: "MERZOUGA", price: 45 },
  { name: "TEMARA", price: 35 },
  { name: "OUAOUIZEGHT", price: 39 },
  { name: "MIDELT", price: 45 },
  { name: "ZAER", price: 35 },
  { name: "AGUELMOUS", price: 39 },
  { name: "RISSANI", price: 45 },
  { name: "AGADIR", price: 35 },
  { name: "TIGHASSALINE", price: 39 },
  { name: "TINGHIR", price: 45 },
  { name: "AIT MELLOUL", price: 35 },
  { name: "AIT ISHAQ", price: 39 },
  { name: "ZAGOURA", price: 45 },
  { name: "INZEGANE", price: 35 },
  { name: "BRADIA", price: 39 },
  { name: "GOULMIMA", price: 45 },
  { name: "TIKIWIN", price: 35 },
  { name: "HAD BOUMOUSSA", price: 39 },
  { name: "SKOURA", price: 45 },
  { name: "TANGER", price: 35 },
  { name: "FOUM OUDI", price: 39 },
  { name: "TAZNAKHT", price: 45 },
  { name: "LAAYAYTA", price: 39 },
  { name: "AGDZ", price: 45 },
  { name: "EL GARA", price: 39 },
  { name: "TANSIFTE", price: 45 },
  { name: "AZEMMOUR", price: 39 },
  { name: "M'HAMID EL GHIZLANE", price: 45 },
  { name: "KHMIS DES ZEMAMRA", price: 39 },
  { name: "TINZOULINE", price: 45 },
  { name: "MOULAY ABDELLAH", price: 39 },
  { name: "TAGHBALT", price: 45 },
  { name: "SIDI BENNOUR", price: 39 },
  { name: "TAMEZMOIUTE", price: 45 },
  { name: "SIDI BOUZID-EL JADIDA", price: 39 },
  { name: "TERNATA", price: 45 },
  { name: "BEN HMED", price: 39 },
  { name: "TAZARINE", price: 45 },
  { name: "DAKHLA", price: 39 },
  { name: "IGHREM N'OUGDAL", price: 45 },
  { name: "OUARZAZATE", price: 39 },
  { name: "AIT BEN HADDOU", price: 45 },
  { name: "TAZA", price: 39 },
  { name: "AMERZGANE", price: 45 },
  { name: "TAOUNATE", price: 39 },
  { name: "AGOUIM", price: 45 },
  { name: "OULAD TAYEB", price: 39 },
  { name: "TABOURAHTE", price: 45 },
  { name: "AIN CHKAF", price: 39 },
  { name: "TABOUNTE OUARZAZATE", price: 45 },
  { name: "MOULAY YACOUB", price: 39 },
  { name: "TIMEDLINE", price: 45 },
  { name: "SAISS", price: 39 },
  { name: "ANZAL", price: 45 },
  { name: "OUED AMLIL", price: 39 },
  { name: "FEZOUATA", price: 45 },
  { name: "AKNOUL", price: 39 },
  { name: "ERROUHA", price: 45 },
  { name: "GUELMIM", price: 39 },
  { name: "AIT BOUDAOUD", price: 45 },
  { name: "BENI ENSAR", price: 39 },
  { name: "TAGOUNITE", price: 45 },
  { name: "BERKANE", price: 39 },
  { name: "BLEIDA", price: 45 },
  { name: "SELOUANE", price: 39 },
  { name: "BENI ZOLI", price: 45 },
  { name: "GUERCIF", price: 39 },
  { name: "NKOUB", price: 45 },
  { name: "SAIDIA", price: 39 },
  { name: "TAMEGROUTE", price: 45 },
  { name: "SIDI HRAZEM", price: 39 },
  { name: "TINEJDAD", price: 45 },
  { name: "ZEGHANGHANE", price: 39 },
  { name: "BOUMALEN DADES", price: 45 },
  { name: "RAS EL MA", price: 39 },
  { name: "ZAIDA", price: 45 },
  { name: "MADGAGH", price: 39 },
  { name: "BOUMIA", price: 45 },
  { name: "BOUARG", price: 39 },
  { name: "MISSOUR", price: 45 },
  { name: "AFRA", price: 39 },
  { name: "AOUFOUS", price: 45 },
  { name: "JAADAR", price: 39 },
  { name: "AIT AISSA OU BRAHIM", price: 45 },
  { name: "LAAYOUNE", price: 39 },
  { name: "AIT TARZOUT", price: 45 },
  { name: "BENGUERIR", price: 39 },
  { name: "ALNIF", price: 45 },
  { name: "CHICHAOUA", price: 39 },
  { name: "AIT SEDRATE SAHL GHARBIA", price: 45 },
  { name: "EL KALAA DES SRAGHNA", price: 39 },
  { name: "MSEMRIR", price: 45 },
  { name: "LAAATAOUIA", price: 39 },
  { name: "AYT IHYA", price: 45 },
  { name: "SEBT GZOULA", price: 39 },
  { name: "BOULMAN", price: 45 },
  { name: "TAMANSOURT", price: 39 },
  { name: "OUTAT EL HAJ", price: 45 },
  { name: "YOUSSOUFIA", price: 39 },
  { name: "AIN CHEGGAG", price: 45 },
  { name: "DAR ESSALAM", price: 39 },
  { name: "AGOURAI", price: 45 },
  { name: "HARBILE", price: 39 },
  { name: "BOURED", price: 45 },
  { name: "TSSOULTANTE", price: 39 },
  { name: "TIZI OUASLI", price: 45 },
  { name: "DOUAR LEHNA", price: 39 },
  { name: "TAHLA", price: 45 },
  { name: "TAMELLALT", price: 39 },
  { name: "GHAFSAI", price: 45 },
  { name: "SKHOUR REHAMNA", price: 39 },
  { name: "AIN AICHA", price: 45 },
  { name: "ECHAMMAIA", price: 39 },
  { name: "BANI WALID", price: 45 },
  { name: "OUALIDIA", price: 39 },
  { name: "BOUHOUDA", price: 45 },
  { name: "SOUIRA GUEDIMA", price: 39 },
  { name: "AIN MEDIOUNA", price: 45 },
  { name: "TLAT BOUGUEDRA", price: 39 },
  { name: "MARNISSA", price: 45 },
  { name: "TAHANAOUT", price: 39 },
  { name: "BAB MARZOUKA", price: 45 },
  { name: "LOUDAYA", price: 39 },
  { name: "TIMAHDITE", price: 45 },
  { name: "GHAZOUA", price: 39 },
  { name: "BOUDERBALA", price: 45 },
  { name: "EL-AFAK", price: 39 },
  { name: "AIN TAOUJDATE", price: 45 },
  { name: "MERS ELKHIR", price: 39 },
  { name: "AZROU", price: 45 },
  { name: "HARHOURA", price: 39 },
  { name: "HAJ KADDOUR", price: 45 },
  { name: "MEHDIA", price: 39 },
  { name: "IFRAN", price: 45 },
  { name: "ROMMANI", price: 39 },
  { name: "IMOUZZER DU KANDAR", price: 45 },
  { name: "BASSATINE EL MENZAH", price: 39 },
  { name: "MOULAY IDRISS ZERHOUNI", price: 45 },
  { name: "KHEMISSET", price: 39 },
  { name: "SEFROU", price: 45 },
  { name: "AIN EL AOUDA", price: 39 },
  { name: "SIDI ADDI", price: 45 },
  { name: "AIN ATTIG", price: 39 },
  { name: "BOUFAKRANE", price: 45 },
  { name: "SALA EL JADIDA", price: 39 },
  { name: "EL HAJEB", price: 45 },
  { name: "SKHIRAT", price: 39 },
  { name: "SKHINATE", price: 45 },
  { name: "TAMESNA", price: 39 },
  { name: "MEJAT", price: 45 },
  { name: "TIFLET", price: 39 },
  { name: "OUISLANE", price: 45 },
  { name: "SIDI BOUKNADEL", price: 39 },
  { name: "M'HAYA", price: 45 },
  { name: "BIOUGRA", price: 39 },
  { name: "SEBT JAHJOUHE", price: 45 },
  { name: "ANZA", price: 39 },
  { name: "GALAZ", price: 45 },
  { name: "DRARGA", price: 39 },
  { name: "HAJRIA OULED DAOUD", price: 45 },
  { name: "OULAD TEIMA", price: 39 },
  { name: "OURTZAGH", price: 45 },
  { name: "TAROUDANT", price: 39 },
  { name: "FRICHA", price: 45 },
  { name: "TIZNIT", price: 39 },
  { name: "KHLALFA", price: 45 },
  { name: "TEMSIA", price: 39 },
  { name: "KARIAT BA MOHAMED", price: 45 },
  { name: "AIT AMIRA", price: 39 },
  { name: "ASSA", price: 45 },
  { name: "CHTOUKA", price: 39 },
  { name: "SIDI IFNI", price: 45 },
  { name: "AOURIR", price: 39 },
  { name: "TAN TAN", price: 45 },
  { name: "TARAST", price: 39 },
  { name: "AHFIR", price: 45 },
  { name: "LEQLIAA", price: 39 },
  { name: "AL AAROUI", price: 45 },
  { name: "DCHEIRA EL JIHADIA", price: 39 },
  { name: "TAOURIRT", price: 45 },
  { name: "CABO NEGRO", price: 39 },
  { name: "JERADA", price: 45 },
  { name: "RENCON", price: 39 },
  { name: "ZAIO", price: 45 },
  { name: "AL HOCEIMA", price: 39 },
  { name: "AKLIM", price: 45 },
  { name: "FNIDEQ", price: 39 },
  { name: "EL AIOUN CHARQIYA", price: 45 },
  { name: "MARTIL", price: 39 },
  { name: "AIN BENI MATHAR", price: 45 },
  { name: "ASSILA", price: 39 },
  { name: "TOUIMA", price: 45 },
  { name: "BAB BERRED", price: 39 },
  { name: "FARKHANA", price: 45 },
  { name: "CHEFCHAOUEN", price: 39 },
  { name: "DRIOUCH", price: 45 },
  { name: "KSAR EL KEBIR", price: 39 },
  { name: "MIDAR", price: 45 },
  { name: "MDIQ", price: 39 },
  { name: "BEN TAIEB", price: 45 },
  { name: "TETOUAN", price: 39 },
  { name: "TIZTOUTINE", price: 45 },
  { name: "BENI CHIKER", price: 45 },
  { name: "FIGUIG", price: 45 },
  { name: "BOUARFA", price: 45 },
  { name: "TENDRARA", price: 45 },
  { name: "ENI DRAR", price: 45 },
  { name: "BOUGHRIBA", price: 45 },
  { name: "AIN ERREGGADA", price: 45 },
  { name: "DAR EL KEBDANI", price: 45 },
  { name: "BOUDINAR", price: 45 },
  { name: "TAMSAMANE", price: 45 },
  { name: "TELAT AZLAF", price: 45 },
  { name: "KASSITA", price: 45 },
  { name: "TAFERSIT", price: 45 },
  { name: "OULED SETTOUT", price: 45 },
  { name: "KARIAT AREKMANE", price: 45 },
  { name: "BENI SIDAL JBEL", price: 45 },
  { name: "MARIOUARI", price: 45 },
  { name: "AFSOU", price: 45 },
  { name: "SAKIA EL HAMRA", price: 45 },
  { name: "BOUJDOUR", price: 45 },
  { name: "ESSEMARA", price: 45 },
  { name: "DEMNATE", price: 45 },
  { name: "JAMAAT SHAIM", price: 45 },
  { name: "TAMESLOUHT", price: 45 },
  { name: "CHWITER", price: 45 },
  { name: "ALOUIDANE", price: 45 },
  { name: "SOUIHLA", price: 45 },
  { name: "OULED HASSOUNE", price: 45 },
  { name: "SIDI MOUSSA", price: 45 },
  { name: "LAHBICHAT", price: 45 },
  { name: "SIDI ABDELLAH GHIYAT", price: 45 },
  { name: "TALMEST", price: 45 },
  { name: "OUNAGHA", price: 45 },
  { name: "AIT DAOUD", price: 45 },
  { name: "BIRKOUATE", price: 45 },
  { name: "AQUERMOUD", price: 45 },
  { name: "TAMANAR", price: 45 },
  { name: "SMIMOU", price: 45 },
  { name: "TIDZI", price: 45 },
  { name: "SIDI KAOUKI", price: 45 },
  { name: "OUAHAT SIDI BRAHIM", price: 45 },
  { name: "HAD DRAA", price: 45 },
  { name: "TAFETACHTE", price: 45 },
  { name: "SIDI ZOUINE", price: 45 },
  { name: "BELAAGUID", price: 45 },
  { name: "ASNI", price: 45 },
  { name: "BEN RAHMOUN", price: 45 },
  { name: "SIDI BOU OTHMANE", price: 45 },
  { name: "CHRIFIA", price: 45 },
  { name: "MESKALA", price: 45 },
  { name: "SEBT BEN SASSI", price: 45 },
  { name: "DOUAR LAARAB", price: 45 },
  { name: "TLET EL HENCHANE", price: 45 },
  { name: "AIT OURIR", price: 45 },
  { name: "OURIKA", price: 45 },
  { name: "ASSAHRIJ", price: 45 },
  { name: "IMINTANOUT", price: 45 },
  { name: "SID L'MOKHTAR", price: 45 },
  { name: "SIDI BOUZID CHICHAOUA", price: 45 },
  { name: "MZOUDIA", price: 45 },
  { name: "MEJJAT", price: 45 },
  { name: "AIT HADI", price: 45 },
  { name: "SIDI CHIKER", price: 45 },
  { name: "IGHOUD", price: 45 },
  { name: "BOUABOUD", price: 45 },
  { name: "AGOUIDIR", price: 45 },
  { name: "OULED MOUMNA", price: 45 },
  { name: "TIMEZGADIOUINE", price: 45 },
  { name: "MECHRA BEL KSIRI", price: 45 },
  { name: "JORF EL MELHA", price: 45 },
  { name: "KHENICHET", price: 45 },
  { name: "MOULAY BOUSSELHAM", price: 45 },
  { name: "EL AARJATE", price: 45 },
  { name: "OULMES", price: 45 },
  { name: "SIDI ALLAL TAZI", price: 45 },
  { name: "TIDDAS", price: 45 },
  { name: "SIDI ALLAL EL BAHRAOUI", price: 45 },
  { name: "SIDI KACEM", price: 45 },
  { name: "SIDI SLIMANE", price: 45 },
  { name: "SOUK EL ARBAA DU GHARB", price: 45 },
  { name: "SIDI YAHYA EL GHARB", price: 45 },
  { name: "SIDI TAIBI", price: 45 },
  { name: "MIRLEFT", price: 45 },
  { name: "IMI OUADDAR", price: 45 },
  { name: "TATA", price: 45 },
  { name: "AOULOUZ", price: 45 },
  { name: "AIT AIAAZA", price: 45 },
  { name: "LAGFIFAT", price: 45 },
  { name: "MASSA", price: 45 },
  { name: "OULAD BERHIL", price: 45 },
  { name: "TALIOUINE", price: 45 },
  { name: "TAMRAGHT", price: 45 },
  { name: "OULED DAHHOU", price: 45 },
  { name: "TAGHAZOUT", price: 45 },
  { name: "AZROU (AGADIR)", price: 45 },
  { name: "BELFAA", price: 45 },
  { name: "SEBT EL GUERDANE", price: 45 },
  { name: "SIDI BIBI", price: 45 },
  { name: "KSAR SGHIR", price: 45 },
  { name: "OUAZZANE", price: 45 },
  { name: "OUED LAOU", price: 45 },
  { name: "IMZOUREN", price: 45 },
  { name: "BAB TAZA", price: 45 },
  { name: "GUESZNAIA", price: 45 },
  { name: "SIDI HSSAIN", price: 45 },
  { name: "MNAR", price: 45 },
  { name: "JEBILA", price: 45 },
  { name: "KHANDAGOUR", price: 45 },
  { name: "LAAOUAMERA", price: 45 },
  { name: "AJDIR (AL HOCEIMA)", price: 45 },
  { name: "BOUKIDAREN", price: 45 },
  { name: "AIT KAMARA", price: 45 },
  { name: "BNI HADIFA", price: 45 },
  { name: "TARGUIST", price: 45 },
  { name: "ISSAGUEN", price: 45 },
  { name: "BNI BOUAYACH", price: 45 },
  { name: "KHEMIS DU SAHEL", price: 45 },
  { name: "ZOUADA", price: 45 },
  { name: "LALLA MIMOUNA", price: 45 },
  { name: "DLALHA", price: 45 },
  { name: "ACHAKKAR", price: 45 },
  { name: "BNI BOUFRAH", price: 45 },
  { name: "AHEJARR ENNEHAL", price: 45 },
  { name: "MELLOUSSA", price: 45 },
  { name: "AIN LAHCEN", price: 45 },
  { name: "BENI HASSANE", price: 45 },
  { name: "BELYOUNECH", price: 45 },
  { name: "AZLA", price: 45 },
  { name: "BNI AHMED CHERQIA", price: 45 },
  { name: "KAA ASRASS", price: 45 },
  { name: "EL JEBEHA", price: 45 },
  { name: "STEHAT", price: 45 },
  { name: "BEN KARRICH", price: 45 },
]

/**
 * Normalise un nom de ville (trim + uppercase + suppression d'accents)
 */
function normalize(s: string): string {
  return s.trim().toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')
}

/**
 * Retourne la City correspondant au nom fourni, ou undefined.
 */
export function findCity(name: string): City | undefined {
  const n = normalize(name)
  return CITIES.find(c => normalize(c.name) === n)
}

/**
 * Calcule le prix de livraison en fonction de la ville et du sous-total.
 * - Retourne 0 si le sous-total >= FREE_DELIVERY_THRESHOLD (499 DH)
 * - Retourne le prix de la ville sinon
 * - Retourne 0 si la ville n'est pas reconnue (à confirmer côté WhatsApp)
 */
export function getDeliveryPrice(cityName: string, subtotal: number): number {
  if (subtotal >= FREE_DELIVERY_THRESHOLD) return 0
  const c = findCity(cityName)
  return c ? c.price : 0
}

/**
 * Liste des noms de villes (triée alphabétiquement) pour les dropdowns.
 */
export const CITY_NAMES: string[] = CITIES.map(c => c.name).sort()
