export interface Product {
  id: string
  name: string
  price: number
  salePrice?: number
  image: string
  collection: string   // 'pyjama' | 'lingerie' | 'pyjama-atach' | 'miss-rose' ou tout slug dynamique venant de Google Sheets
  collectionLabel?: string   // libellé original (ex: "Collection" Sheets) pour affichage si collection est un slug généré
  colors: string[]
  colorImages?: Record<string, string>   // couleur → suffixe image (ex: 'Gris' → 'a2')
  colorGalleries?: Record<string, string[]>   // couleur → liste de toutes les images (Sheet, multi-image)
  colorPrices?: Record<string, { price: number; salePrice?: number }>   // couleur → prix spécifique (sinon fallback sur price/salePrice)
  sizes: string[]
  rating: number
  reviews: number
  description: string
  features: string[]
  inStock: boolean
  badge?: 'bestseller' | 'new' | 'sale'
  details?: {
    image1: string
    image2?: string
  }

}

export const products: Product[] = [

  // ─── Collection Pyjama ───────────────────────────────────────────────────────
  {
    id: '1',
    name: 'Ensemble Arc-en-ciel',
    price: 350,
    salePrice: 240,
    image: 'summer-light',
    collection: 'pyjama',
    colors: ['Rose', 'beige'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.6,
    reviews: 187,
    description: 'Pyjama Femme , Automne-Printemps, hiver',
    features: ['Tissu aéré', 'Séchage rapide', 'Léger', 'Respirant'],
    inStock: true,
    badge: 'sale',
    details: {
      image1: '/images/details/product-1-detail-1.jpg',
      image2: '/images/details/product-1-detail-2.jpg',
    },
  },
  {
    id: '2',
    name: 'Ensemble Cœur Élégant',
    price: 240,
    image: 'linen-breeze',
    collection: 'pyjama',
    colors: ['Rose', 'gris'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.5,
    reviews: 143,
    description: 'Pyjama Femme , Automne-Printemps, hiver',
    features: ['Lin 100%', 'Très léger', 'Froisse naturellement', 'Écologique'],
    inStock: true,
    details: {
      image1: '/images/details/product-2-detail-1.jpg',
      image2: '/images/details/product-2-detail-2.jpg',
    },
  },
  {
    id: '3',
    name: 'Ensemble Mini Moon',
    price: 250,
    image: 'winter-cozy',
    collection: 'pyjama',
    colors: ['blanc', 'beige', 'vert'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 312,
    description: 'Pyjama Femme , Automne-Printemps, hiver',
    features: ['Intérieur molletonné', 'Très chaud', 'Confortable', 'Respirant'],
    inStock: true,
    details: {
      image1: '/images/details/product-3-detail-1.jpg',
      image2: '/images/details/product-3-detail-2.jpg',
    },
  },
  {
    id: '4',
    name: 'Ensemble Motif Tressé',
    price: 220,
    image: 'cashmere-winter',
    collection: 'pyjama',
    colors: ['vert', 'beige'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 145,
    description: 'Pyjama Femme , Automne-Printemps, hiver',
    features: ['Cachemire véritable', 'Extrêmement chaud', 'Luxueux', 'Durable'],
    inStock: true,
    details: {
      image1: '/images/details/product-4-detail-1.jpg',
      image2: '/images/details/product-4-detail-2.jpg',
    },
  },
  {
    id: '5',
    name: 'Ensemble Chic Rayé',
    price: 230,
    image: 'silk-luxury',
    collection: 'pyjama',
    colors: ['Rose', 'bleu'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 234,
    description: 'Pyjama Femme , Automne-Printemps, hiver',
    features: ['Soie naturelle 100%', 'Anti-transpiration', 'Thermorégulation', 'Boutons nacre'],
    inStock: true,
    badge: 'bestseller',
    details: {
      image1: '/images/details/product-5-detail-1.jpg',
      image2: '/images/details/product-5-detail-2.jpg',
    },
  },
  {
    id: '6',
    name: 'Ensemble Petit Ourson',
    price: 240,
    image: 'cotton-premium',
    collection: 'pyjama',
    colors: ['Rose', 'beige'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 456,
    description: 'Pyjama Femme , Automne-Printemps, hiver',
    features: ['Coton égyptien', 'Très durable', 'Hypoallergénique', 'Anti-boulochage'],
    inStock: true,
    badge: 'bestseller',
    details: {
      image1: '/images/details/product-6-detail-1.jpg',
      image2: '/images/details/product-6-detail-2.jpg',
    },
  },
  {
    id: '7',
    name: 'Ensemble Signature Douceur',
    price: 240,
    image: 'bamboo-eco',
    collection: 'pyjama',
    colors: ['Rose', 'beige'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 289,
    description: 'Pyjama Femme , Automne-Printemps, hiver',
    features: ['Bambou durable', 'Écologique', 'Ultra doux', 'Thermorégulation'],
    inStock: true,
    badge: 'new',
    details: {
      image1: '/images/details/product-7-detail-1.jpg',
      image2: '/images/details/product-7-detail-2.jpg',
    },
  },

  // ─── Collection Pyjama Prestige ──────────────────────────────────────────────
  {
    id: 'a1',
    name: 'Ensemble Nuit Velours',
    price: 290,
    image: 'a1',
    collection: 'pyjama-atach',
    colors: ['Noir/Blanc', 'Rose', 'Gris', 'Rose Bébé'],
    colorImages: {
      'Noir/Blanc': 'a1',
      'Rose':       'a1-Rose',
      'Gris':       'a1-gris',
      'Rose Bébé':  'a1-rosebebe',
    },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.8,
    reviews: 62,
    description: 'Pyjama manches longues — coupe élégante, tissu doux et chaud. Modèle DIOR.',
    features: ['Manches longues', 'Tissu chaud & doux', 'Coupe ajustée', 'Fermeture boutonnée'],
    inStock: true,
    badge: 'bestseller',
  },
  {
    id: 'a2',
    name: 'Ensemble Pastel Prestige',
    price: 280,
    image: 'a2',
    collection: 'pyjama-atach',
    colors: ['Gris', 'Rose', 'Mauve', 'Rose Pastel'],
    colorImages: {
      'Gris':        'a2',
      'Rose':        'a2-rose',
      'Mauve':       'a2-mauve',
      'Rose Pastel': 'a2-rose2',
    },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviews: 48,
    description: 'Pyjama demi-manches aux teintes pastel douces et apaisantes. Modèle LUIS VUITTON.',
    features: ['Demi-manches', 'Palette pastel', 'Tissu respirant', 'Confort toute la nuit'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'a3',
    name: 'Ensemble Minuit Raffiné',
    price: 280,
    image: 'a3',
    collection: 'pyjama-atach',
    colors: ['Noir/Blanc'],
    colorImages: {
      'Noir/Blanc': 'a3',
    },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.6,
    reviews: 35,
    description: 'Pyjama demi-manches motif FF — sobre, chic et intemporel. Modèle FENDI.',
    features: ['Demi-manches', 'Motif FF signature', 'Tissu satiné', 'Finitions soignées'],
    inStock: true,
  },
  {
    id: 'a4',
    name: 'Ensemble Céleste Satiné',
    price: 280,
    image: 'a4',
    collection: 'pyjama-atach',
    colors: ['Blanc', 'Bleu Ciel', 'Bleu Marine'],
    colorImages: {
      'Blanc': 'a4',
      'Bleu Ciel': 'a4-bleu-ciel',
      'Bleu Marine': 'a4-bleu',
    },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviews: 54,
    description: 'Pyjama manches longues aux teintes azur et célestes. Modèle VICTORIA SECRET.',
    features: ['Manches longues', 'Teintes fraîches & lumineuses', 'Matière douce', 'Coupe féminine'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'a5',
    name: 'Ensemble Jardin Fleuri',
    price: 280,
    image: 'a5',
    collection: 'pyjama-atach',
    colors: ['Blanc Fleuri', 'Rose GG', 'Fleurs'],
    colorImages: {
      'Blanc Fleuri': 'a5',
      'Rose GG':      'a5-rose',
      'Fleurs':       'a5-fleur',
    },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.8,
    reviews: 71,
    description: 'Pyjama demi-manches aux motifs floraux Gucci. Modèle GUCCI Floral.',
    features: ['Demi-manches', 'Motifs floraux', 'Tissu satiné premium', 'Édition limitée'],
    inStock: true,
    badge: 'bestseller',
  },
  {
    id: 'a6',
    name: "Ensemble Zéphyr d'Été",
    price: 270,
    image: 'a6',
    collection: 'pyjama-atach',
    colors: ['Zèbre', 'Bleu', 'Noir', 'Floral Sombre'],
    colorImages: {
      'Zèbre': 'a6',
      'Bleu': 'a6-bleu',
      'Noir': 'a6-noir',
      'Floral Sombre': 'a6-dark',
    },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviews: 43,
    description: "Pyjama short — léger et aéré, parfait pour les nuits d'été. Modèle COCOLARSI.",
    features: ['Short confortable', 'Tissu léger & aéré', 'Motif zèbre disponible', 'Idéal été'],
    inStock: true,
  },
  {
    id: 'a7',
    name: 'Ensemble Rosée Dorée',
    price: 270,
    image: 'a7',
    collection: 'pyjama-atach',
    colors: ['Rose Intense'],
    colorImages: { 'Rose Intense': 'a7' },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.6,
    reviews: 29,
    description: 'Pyjama short rose — féminité et douceur pour des nuits sereines. Modèle DIOR Short.',
    features: ['Short doux', 'Coloris rose tendre', 'Coupe féminine', 'Tissu confortable'],
    inStock: true,
  },
  {
    id: 'a8',
    name: 'Ensemble Lilas Prestige',
    price: 270,
    image: 'a8',
    collection: 'pyjama-atach',
    colors: ['Mauve', 'Gris'],
    colorImages: {
      'Mauve': 'a8',
      'Gris': 'a8-gris',
    },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviews: 38,
    description: 'Pyjama short aux teintes mauve et gris — élégance discrète et raffinée. Modèle LUIS VUITTON Short.',
    features: ['Short élégant', 'Teintes douces & raffinées', 'Tissu respirant', 'Confort premium'],
    inStock: true,
  },
  {
    id: 'a9',
    name: 'Ensemble Caramel Doré',
    price: 270,
    image: 'a9',
    collection: 'pyjama-atach',
    colors: ['Marron Caramel'],
    colorImages: { 'Marron Caramel': 'a9' },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviews: 22,
    description: 'Pyjama short marron caramel — chaleureux et tendance. Modèle FENDI Short.',
    features: ['Short tendance', 'Ton caramel chaud', 'Tissu doux', 'Style contemporain'],
    inStock: true,
  },
  {
    id: 'a10',
    name: 'Ensemble Brise Florale',
    price: 200,
    image: 'a10',
    collection: 'pyjama-atach',
    colors: ['Rose Fleuri'],
    colorImages: { 'Rose Fleuri': 'a10' },
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.6,
    reviews: 31,
    description: 'Pyjama sans manches aux motifs floraux — légèreté absolue pour les nuits chaudes. Modèle LUIS VUITTON Sans Manche.',
    features: ['Sans manches', 'Motifs floraux printaniers', 'Ultra léger', 'Idéal été & printemps'],
    inStock: true,
    badge: 'new',
  },


  // ─── Collection Lingerie (source : Excel GESTION_DE_STOCK) ──────────────────
  {
    id: 'l1',
    name: 'Ensemble Élégance',
    price: 120,
    image: 'lingerie-1',
    collection: 'lingerie',
    colors: ['NOIR/VERT', 'NOIR/ROUGE', 'NOIR/ROSE', 'BLEU/ROSE', 'NOIR/MARRON', 'ROSE/ROSE', 'JAUNE', 'BLANC/ROSE'],
    colorImages: {
      'JAUNE':      'l1-jaune',
      'BLANC/ROSE': 'l1-blanc-rose',
    },
    sizes: ['75', '80', '85', '90'],
    rating: 4.7,
    reviews: 89,
    description: 'Ensemble lingerie bicolore — soutien-gorge & culotte assortis, modèle A130',
    features: ['Bicolore raffiné', 'Matière douce', 'Maintien optimal', 'Ensemble assorti'],
    inStock: true,
    badge: 'new',
    details: {
      image1: '/images/details/product-l1-detail-1.jpg',
    },
  },
  {
    id: 'l2',
    name: 'Ensemble Passion',
    price: 120,
    image: 'lingerie-2',
    collection: 'lingerie',
    colors: ['ROUGE/NOIR', 'NOIR/ROUGE', 'JAUNE', 'BLANC', 'NOIR', 'BLEU', 'ROSE', 'ROUGE', 'ROUGE/VERT'],
    colorImages: {
      'BLANC':      'l2-blanc',
      'NOIR':       'l2-noir',
      'BLEU':       'l2-bleu',
      'ROSE':       'l2-rose',
      'ROUGE':      'l2-rouge',
      'ROUGE/VERT': 'l2-rouge-vert',
    },
    sizes: ['75', '80', '85', '90'],
    rating: 4.6,
    reviews: 74,
    description: 'Ensemble lingerie audacieux — coloris vifs et contrastés, modèle A133',
    features: ['Coloris intenses', 'Dentelle fine', 'Confort toute journée', 'Coupe flatteuse'],
    inStock: true,
    details: {
      image1: '/images/details/product-l2-detail-1.jpg',
    },
  },
  {
    id: 'l3',
    name: 'Ensemble Classique',
    price: 130,
    image: 'lingerie-3',
    collection: 'lingerie',
    colors: ['NOIR', 'BLEU', 'BLANC', 'ROUGE', 'VERT'],
    colorImages: {
      'BLANC': 'l3-blanc',
      'ROUGE': 'l3-rouge',
      'VERT':  'l3-vert',
    },
    sizes: ['90', '95', '100'],
    rating: 4.5,
    reviews: 61,
    description: 'Ensemble lingerie grandes tailles — élégance intemporelle, modèle A136',
    features: ['Grandes tailles', 'Maintien renforcé', 'Tissu confortable', 'Coupe adaptée'],
    inStock: true,
    details: {
      image1: '/images/details/product-l3-detail-1.jpg',
    },
  },
  {
    id: 'l4',
    name: 'Ensemble Séduction Big size',
    price: 130,
    image: 'lingerie-4',
    collection: 'lingerie',
    colors: ['NOIR/ROUGE', 'BLEU/VERT', 'BLANC/ROSE', 'BLANC/BLEU', 'ROSE', 'ROUGE/ROUGE', 'ROUGE/VERT', 'BLANC/MAUVE'],
    colorImages: {
      'ROSE':        'l4-rose',
      'ROUGE/ROUGE': 'l4-rouge-rouge',
      'ROUGE/VERT':  'l4-rouge-vert',
      'BLANC/MAUVE': 'l4-blanc-mauve',
    },
    sizes: ['90', '95', '100'],
    rating: 4.8,
    reviews: 103,
    description: 'Ensemble lingerie séduisant grandes tailles — bicolore élégant, modèle A137',
    features: ['Bicolore élégant', 'Grandes tailles', 'Dentelle brodée', 'Finitions premium'],
    inStock: true,
    badge: 'bestseller',
    details: {
      image1: '/images/details/product-l4-detail-1.jpg',
    },
  },
  {
    id: 'l5',
    name: 'Ensemble Romance',
    price: 140,
    image: 'lingerie-5',
    collection: 'lingerie',
    colors: ['BLEU/VERT', 'BLEU/BLANC', 'ROSE/VERT'],
    sizes: ['75', '80', '85', '90'],
    rating: 4.7,
    reviews: 88,
    description: 'Ensemble lingerie romantique — teintes douces et naturelles, modèle A170',
    features: ['Teintes naturelles', 'Ultra doux', 'Respirant', 'Confort premium'],
    inStock: true,
    badge: 'new',
    details: {
      image1: '/images/details/product-l5-detail-1.jpg',
    },
  },
  {
    id: 'l6',
    name: 'Ensemble Rosée',
    price: 120,
    image: 'lingerie-6',
    collection: 'lingerie',
    colors: ['ROSE/ROUGE'],
    sizes: ['75', '80', '85', '90'],
    rating: 4.5,
    reviews: 47,
    description: 'Ensemble lingerie délicat — rosé et rouge, féminité assurée, modèle A230',
    features: ['Féminin et délicat', 'Matière soyeuse', 'Coupe ajustée', 'Bretelles réglables'],
    inStock: true,
  },
  {
    id: 'l7',
    name: 'Ensemble Intense',
    price: 120,
    image: 'lingerie-7',
    collection: 'lingerie',
    colors: ['ROUGE', 'NOIR'],
    sizes: ['80', '85', '90', '95'],
    rating: 4.6,
    reviews: 92,
    description: 'Ensemble lingerie intense — coloris forts et audacieux, modèle A240',
    features: ['Coloris intenses', 'Maintien renforcé', 'Élastique doux', 'Tissu résistant'],
    inStock: true,
    details: {
      image1: '/images/details/product-l7-detail-1.jpg',
    },
  },
  {
    id: 'l8',
    name: 'Ensemble Flora',
    price: 130,
    image: 'lingerie-8',
    collection: 'lingerie',
    colors: ['ROSE/VERT', 'BLEU/VERT'],
    sizes: ['75', '80', '85', '90'],
    rating: 4.8,
    reviews: 76,
    description: 'Ensemble lingerie floral — inspiré de la nature, fraîcheur garantie, modèle G281',
    features: ['Inspiré nature', 'Bicolore frais', 'Confort léger', 'Coupe flatteuse'],
    inStock: true,
    badge: 'new',
    details: {
      image1: '/images/details/product-l8-detail-1.jpg',
    },
  },
  {
    id: 'l9',
    name: 'Ensemble Signature',
    price: 180,
    image: 'lingerie-9',
    collection: 'lingerie',
    colors: ['NOIR/ROUGE', 'BLANC'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 54,
    description: 'Robe de chambre Gown premium — élégance signature, modèle A400',
    features: ['Tissu fluide', 'Coupe longue', 'Finitions luxe', 'Idéal cadeau'],
    inStock: true,
    badge: 'bestseller',
    details: {
      image1: '/images/details/product-l9-detail-1.jpg',
    },
  },

  {
    id: 'l10',
    name: 'Ensemble Raffiné',
    price: 140,
    image: 'l10',
    collection: 'lingerie',
    colors: ['MAUVE', 'BLANC', 'ROSE', 'BORDEAUX', 'BLEU'],
    colorImages: {
      'MAUVE':    'l10',
      'BLANC':    'l10-blanc',
      'ROSE':     'l10-rose',
      'BORDEAUX': 'l10-bordeaux',
      'BLEU':     'l10-bleu',
    },
    sizes: ['75', '80', '85', '90'],
    rating: 4.7,
    reviews: 0,
    description: 'Ensemble lingerie raffiné — silhouette féminine et teintes délicates, modèle A310',
    features: ['Matière douce', 'Coupe ajustée', 'Large palette de couleurs', 'Maintien optimal'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'l11',
    name: 'Ensemble Douceur Satin',
    price: 150,
    image: 'l11',
    collection: 'lingerie',
    colors: ['ROSE', 'BORDEAUX', 'NOIR', 'BLANC', 'ORANGE'],
    colorImages: {
      'ROSE':     'l11',
      'BORDEAUX': 'l11-bordeaux',
      'NOIR':     'l11-noir',
      'BLANC':    'l11-blanc',
      'ORANGE':   'l11-orange',
    },
    sizes: ['75', '80', '85', '90'],
    rating: 4.7,
    reviews: 0,
    description: 'Ensemble lingerie satin doux — élégance féminine et confort toute journée, modèle A171',
    features: ['Satin doux', 'Couleurs riches', 'Coupe flatteuse', 'Dentelle fine'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'l12',
    name: 'Ensemble Jardin Floral',
    price: 170,
    image: 'l12',
    collection: 'lingerie',
    colors: ['BLANC FLEURI', 'NOIR', 'VERT', 'BLANC/ROUGE', 'ROUGE/VERT'],
    colorImages: {
      'BLANC FLEURI': 'l12',
      'NOIR':         'l12-noir',
      'VERT':         'l12-vert',
      'BLANC/ROUGE':  'l12-blanc-rouge',
      'ROUGE/VERT':   'l12-rouge-vert',
    },
    sizes: ['75', '80', '85', '90'],
    rating: 4.8,
    reviews: 0,
    description: 'Ensemble lingerie floral — inspiré des jardins en fleurs, romantique et bicolore, modèle A170',
    features: ['Motif floral', 'Bicolore élégant', 'Tissu respirant', 'Féminité naturelle'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'l13',
    name: 'Ensemble Velours Ardent',
    price: 140,
    image: 'l13',
    collection: 'lingerie',
    colors: ['ROUGE', 'BLANC', 'NOIR'],
    colorImages: {
      'ROUGE': 'l13',
      'BLANC': 'l13-blanc',
      'NOIR':  'l13-noir',
    },
    sizes: ['75', '80', '85', '90'],
    rating: 4.6,
    reviews: 0,
    description: 'Ensemble lingerie ardent — coloris forts et désirables pour une séduction assumée, modèle A470',
    features: ['Coloris intenses', 'Maintien parfait', 'Tissu confortable', 'Coupe séduisante'],
    inStock: true,
  },
  {
    id: 'l14',
    name: 'Ensemble Broderie Douce',
    price: 150,
    image: 'l14',
    collection: 'lingerie',
    colors: ['BORDEAUX', 'ROSE', 'PISTACHE', 'BLEU'],
    colorImages: {
      'BORDEAUX': 'l14',
      'ROSE':     'l14-rose',
      'PISTACHE': 'l14-pistache',
      'BLEU':     'l14-bleu',
    },
    sizes: ['75', '80', '85', '90'],
    rating: 4.7,
    reviews: 0,
    description: 'Ensemble lingerie broderie douce — teintes douces et décors brodés pour une féminité subtile, modèle A122',
    features: ['Broderie délicate', 'Teintes douces', 'Tissu doux', 'Confort prolongé'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'l15',
    name: 'Ensemble Multicolore',
    price: 100,
    image: 'l15',
    collection: 'lingerie',
    colors: ['MULTICOLORE', 'MULTICOLORE 2'],
    colorImages: {
      'MULTICOLORE':   'l15',
      'MULTICOLORE 2': 'l15-2',
    },
    sizes: ['S-M', 'L-XL', 'XXL'],
    rating: 4.5,
    reviews: 0,
    description: 'Ensemble lingerie multicolore — imprimés colorés et joyeux pour toutes les morphologies, modèle K101',
    features: ['Multicolore vivant', 'Grandes tailles disponibles', 'Tissu confortable', 'Style casual'],
    inStock: true,
  },

  // ─── Collection Miss Rose ─────────────────────────────────────────────────
  {
    id: 'mr1',
    name: 'Victoria Secret',
    price: 150,
    image: 'mr1',
    collection: 'miss-rose',
    colors: ['Rose'],
    colorImages: {
      'Rose': 'mr1',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 62,
    description: 'Pyjama Miss Rose — Victoria Secret, coupe élégante et féminine.',
    features: ['Tissu doux', 'Coupe ajustée', 'Féminité assurée', 'Confort optimal'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'mr2',
    name: 'Satin Élégance',
    price: 150,
    image: 'mr2',
    collection: 'miss-rose',
    colors: ['Noir', 'Beige', 'Rouge'],
    colorImages: {
      'Noir':  'mr2',
      'Beige': 'mr2-beige',
      'Rouge': 'mr2-rouge',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 88,
    description: 'Pyjama Miss Rose — Satin Élégance, brillance soyeuse et confort raffiné.',
    features: ['Satin premium', 'Brillance naturelle', 'Très doux', 'Tombé parfait'],
    inStock: true,
    badge: 'bestseller',
  },
  {
    id: 'mr3',
    name: 'Pyjama Coton Doux',
    price: 100,
    image: 'mr3',
    collection: 'miss-rose',
    colors: ['Bleu', 'Rose'],
    colorImages: {
      'Bleu': 'mr3',
      'Rose': 'mr3-rose',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.6,
    reviews: 47,
    description: 'Pyjama Miss Rose — Coton Doux, légèreté et respirabilité pour les nuits douces.',
    features: ['Coton léger', 'Respirant', 'Doux sur la peau', 'Idéal toutes saisons'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'mr4',
    name: 'Collection Aïd',
    price: 70,
    image: 'mr4',
    collection: 'miss-rose',
    colors: ['Bleu Ciel', 'Jaune', 'Saumon'],
    colorImages: {
      'Bleu Ciel': 'mr4',
      'Jaune':     'mr4-jaune',
      'Saumon':    'mr4-saumon',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 53,
    description: 'Pyjama Miss Rose — Collection Aïd, coloris festifs et élégants.',
    features: ['Coloris festifs', 'Coupe moderne', 'Tissu confortable', 'Idéal occasion'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'mr5',
    name: 'Motif Léopard',
    price: 100,
    image: 'mr5',
    collection: 'miss-rose',
    colors: ['Léopard'],
    colorImages: {
      'Léopard': 'mr5',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.5,
    reviews: 38,
    description: 'Pyjama Miss Rose — Motif Léopard, imprimé tendance et audacieux.',
    features: ['Imprimé léopard', 'Tendance', 'Coupe décontractée', 'Tissu souple'],
    inStock: true,
  },
  {
    id: 'mr6',
    name: 'Velours',
    price: 110,
    image: 'mr6',
    collection: 'miss-rose',
    colors: ['Gris', 'Saumon', 'Vert'],
    colorImages: {
      'Gris':   'mr6',
      'Saumon': 'mr6-saumon',
      'Vert':   'mr6-vert',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 71,
    description: 'Pyjama Miss Rose — Velours Ali, chaleur douce et toucher velouté.',
    features: ['Velours premium', 'Très chaud', 'Toucher doux', 'Coupe confortable'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'mr7',
    name: 'Motif Fraise',
    price: 120,
    image: 'mr7',
    collection: 'miss-rose',
    colors: ['Rose', 'Vert'],
    colorImages: {
      'Rose': 'mr7',
      'Vert': 'mr7-vert',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.6,
    reviews: 44,
    description: 'Pyjama Miss Rose — Motif Fraise, imprimé fruité et coloré pour les nuits joyeuses.',
    features: ['Motif fraise', 'Coloré et gai', 'Tissu léger', 'Confort toute nuit'],
    inStock: true,
  },
  {
    id: 'mr8',
    name: 'Pyjama Doré',
    price: 135,
    image: 'mr8',
    collection: 'miss-rose',
    colors: ['Gris', 'Marron', 'Noir'],
    colorImages: {
      'Gris':   'mr8',
      'Marron': 'mr8-marron',
      'Noir':   'mr8-noir',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 96,
    description: 'Pyjama Miss Rose — Doré, finitions dorées et élégance de nuit.',
    features: ['Finitions dorées', 'Tissu luxueux', 'Coupe flatteuse', 'Idéal cadeau'],
    inStock: true,
    badge: 'bestseller',
  },
  {
    id: 'mr9',
    name: 'Cocooning Velours',
    price: 100,
    image: 'mr9',
    collection: 'miss-rose',
    colors: ['Bleu', 'Bordeaux', 'Noir', 'Vert'],
    colorImages: {
      'Bleu':     'mr9',
      'Bordeaux': 'mr9-bordeaux',
      'Noir':     'mr9-noir',
      'Vert':     'mr9-vert',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 58,
    description: 'Pyjama Miss Rose — Cocooning Velours, douceur enveloppante pour les soirées cosy.',
    features: ['Velours cocooning', 'Ultra doux', 'Chaud et confortable', 'Large choix de couleurs'],
    inStock: true,
    badge: 'new',
  },
  {
    id: 'mr10',
    name: 'Twin Set Rayé',
    price: 125,
    image: 'mr10',
    collection: 'miss-rose',
    colors: ['Gris', 'Rose'],
    colorImages: {
      'Gris': 'mr10',
      'Rose': 'mr10-rose',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.6,
    reviews: 41,
    description: 'Pyjama Miss Rose — Twin Set Rayé, ensemble coordonné à rayures classiques.',
    features: ['Motif rayé', 'Ensemble assorti', 'Tissu respirant', 'Style casual chic'],
    inStock: true,
  },
  {
    id: 'mr11',
    name: 'Tafeta Chic',
    price: 140,
    image: 'mr11',
    collection: 'miss-rose',
    colors: ['Gris', 'Marron', 'Vert'],
    colorImages: {
      'Gris':   'mr11',
      'Marron': 'mr11-marron',
      'Vert':   'mr11-vert',
    },
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 67,
    description: 'Pyjama Miss Rose — Tafeta Chic, tissu taffetas soyeux pour une nuit élégante.',
    features: ['Taffetas premium', 'Brillance élégante', 'Tombé fluide', 'Finitions soignées'],
    inStock: true,
    badge: 'new',
  },
]

export const getProductById = (id: string): Product | undefined => {
  return products.find((p) => p.id === id)
}

export const getProductsByCollection = (collection: Product['collection']): Product[] => {
  return products.filter((p) => p.collection === collection)
}

export const getBestSellers = (): Product[] => {
  return products.filter((p) => p.badge === 'bestseller').slice(0, 6)
}

export const getNewProducts = (): Product[] => {
  return products.filter((p) => p.badge === 'new')
}

export const getSaleProducts = (): Product[] => {
  return products.filter((p) => p.salePrice)
}
